### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by julianfairfax** [Efreak/seeker-fdroid#1]
Hi,
I have forked your repo with the intent to create my own. I have followed your guide, but I now have a problem. I'm getting this error:   Error: Process completed with exit code 1. in the run update script section of the action: https://github.com/julianfairfax/fdroid-repo/runs/6905718500?check_suite_focus=true. Do you know how I can fix this? Thanks for your help!

**Comment by Efreak** [comment]
[You need a valid index-v1.json](https://github.com/julianfairfax/fdroid-repo/runs/6905718500?check_suite_focus=true#step:8:21) for @xarantolus metascoop program to run. Since you need to run fdroid locally once anyways to get your config.py set up, I didn't think it was necessary to keep the existing file in the template. This repo is actually a fork of [xarantolus/fdroid-action](https://GitHub.com/xarantolus/fdroid-action), which is the original (my template fork is at [efreak/fdroid-action](https://GitHub.com/efreak/fdroid-action); GitHub only allows one in-network fork per user that links back to the original, so seeker-fdroid and [auto-daily-fdroid](https://GitHub.com/efreak/auto-daily-fdroid) aren't shown as forks) .

Run `fdroid update` after you set up your config.py and add the `index-v1.json` to the repo. I'll check soon to make sure there's a blank index-v1.json in the fdroid-action repo.

**Comment by julianfairfax** [comment]
The build is still running so it hasn't explicitly failed yet, but running fdroid update in the fdroid folder didn't create and index-v1.json file. Just an index.xml file. Output is here:
```
2022-06-16 07:55:10,842 INFO: Using /opt/android-sdk/build-tools/30.0.3/apksigner 
2022-06-16 07:55:10,843 WARNING: repo_icon "repo/icons/icon.png" does not exist! Check "config.yml".
2022-06-16 07:55:11,549 INFO: Creating signed index with this key (SHA256):
2022-06-16 07:55:11,549 INFO: 56 1A D8 00 D9 00 CA 8E BF 3A 53 1C 6A 86 0B 5A B8 56 9D 0D 37 6F D1 21 CB CC FC A9 43 4D 7D F7
2022-06-16 07:55:11,550 CRITICAL: OSError while trying to execute jar cf index.jar index.xml: [Errno 2] No such file or directory: 'jar'
```

**Comment by xarantolus** [comment]
Which version of the `fdroid` command-line tool are you using locally to set it up? I think there's a version 1 that is in most default package repositories, but the metascoop tool is made to work with version 2, which is why the Action runs `sudo add-apt-repository ppa:fdroid/fdroidserver` to be able to install the latest version.

Also the old version used a `config.py`, but now it should only be a yaml file; no need to/shouldn't create the `config.py`.

Also maybe the `jar` command is missing because the Java installation has failed in some way, but not sure (I mean, usually that should give an error?).

**Comment by julianfairfax** [comment]
> Which version of the `fdroid` command-line tool are you using locally to set it up? I think there's a version 1 that is in most default package repositories, but the metascoop tool is made to work with version 2, which is why the Action runs `sudo add-apt-repository ppa:fdroid/fdroidserver` to be able to install the latest version.
> 
> Also the old version used a `config.py`, but now it should only be a yaml file; no need to/shouldn't create the `config.py`.
> 
> Also maybe the `jar` command is missing because the Java installation has failed in some way, but not sure (I mean, usually that should give an error?).

It's version 2: https://aur.archlinux.org/packages/fdroidserver

I followed the setup guide to the letter. So whatever I do or don't have is whatever was mentioned in there. I did have to change qrcode.svg to qrcode.png

I don't know. I have Java 8 and 11 installed. 8 was installed by default and sdkmanager needs it, whereas I installed 11 when I installed android-sdk and gradlew needs it.

**Comment by Efreak** [comment]
As I mentioned, it requires index-v1.json. The error in your action clearly states this. Adding an xml file won't fix this.

```
git remote add upstream https://github.com/Efreak/fdroid-action
git fetch
git cherry-pick 126fea
git push
```

**Comment by julianfairfax** [comment]
> As I mentioned, it requires index-v1.json. The error in your action clearly states this. Adding an xml file won't fix this.
> 
> ```
> git remote add upstream https://github.com/Efreak/fdroid-action
> git fetch
> git cherry-pick 126fea
> git push
> ```

This should be added to the setup.md file. Although you need to run `git fetch upstream main`, not just `git fetch`

**Comment by julianfairfax** [comment]
How do I change the name though? https://github.com/julianfairfax/fdroid-repo/commit/949f926204677877cff30d32e3e596105c400dcb didn't work.

**Comment by xarantolus** [comment]
I think the name is taken from the `config.yaml` file, so you need to update the repo secret

**Comment by julianfairfax** [comment]
> I think the name is taken from the `config.yaml` file, so you need to update the repo secret

I don't have one of those in my repo. And the config.yml file the setup.md said to make (https://github.com/Efreak/seeker-fdroid/blob/main/setup.md#install--initialize-your-f-droid-repository) is ignored by git

**Comment by xarantolus** [comment]
> I don't have one of those in my repo.

Yes, but in your repo secrets there's a `CONFIG_YML` that is used to create the `config.yaml` file. 

Change your local `config.yaml` file (the `repo_name` key specifically) and then add it as repo secret again.

**Comment by Efreak** [comment]
@julianfairfax you've got your key store included in your repo, I recommend using secrets for that.

**Comment by julianfairfax** [comment]
> @julianfairfax you've got your key store included in your repo, I recommend using secrets for that.

Why do I have to do that? You can't use this keystore without a password. This is the one for building apps btw, not for the repo.
