### ISSUE TITLE
Limit to one release

### ISSUE THREAD

**Issue by julianfairfax** [Efreak/seeker-fdroid#3]
Is it possible to limit the code to only add the latest release to the repo? I don't need each one available and it increases size a lot.

**Comment by Efreak** [comment]
I'll take a look over the weekend. The easy way to do this is to set the number of releases to fetch to only one, then to remove the releases before fetching updates; this will cause the metascoop binary to only fetch the last release and any given checkout will now have only one release. You'll also want to modify the action to *amend the previous commit* each time instead of adding a new commit, and force push, otherwise you're still keeping all those binaries you don't want in history.

The best way to do this would probably be to not use git to begin with, and simply use a vps or your PC to upload files to a static host.

**Comment by julianfairfax** [comment]
> I'll take a look over the weekend. The easy way to do this is to set the number of releases to fetch to only one, then to remove the releases before fetching updates; this will cause the metascoop binary to only fetch the last release and any given checkout will now have only one release. You'll also want to modify the action to _amend the previous commit_ each time instead of adding a new commit, and force push, otherwise you're still keeping all those binaries you don't want in history.
> 
> The best way to do this would probably be to not use git to begin with, and simply use a vps or your PC to upload files to a static host.

Oh yeah true history. It would still be nice to know how to set the number of releases to only one though because then at least it would collect overtime instead of fetching the whole history of the releases even when building from scratch.

**Comment by Efreak** [comment]
This is the commit you want, just change the 5 releases per page to 1 release per page: [auto-daily-fdroid#3dc937](https://github.com/Efreak/auto-daily-fdroid/commit/3dc937411dd4fc7b3f3b24571b22201850eeb71e) (patch [here](https://github.com/Efreak/auto-daily-fdroid/commit/3dc937411dd4fc7b3f3b24571b22201850eeb71e.patch) for `git apply`). It would be nice if the number of releases was configurable but :shrug: it's easier to work with what's here, and I don't intend to modify the program that much; I'd be more likely to just use [gh](https://www.github.com/cli/cli)

**Comment by julianfairfax** [comment]
I'm not using this code anymore, and I also won't be subscribing to this issue again (mention me if you need me), but I am dropping by to say that (at least with GitLab), deploying the built repo to GitLab (or GitHub) Pages, fixes the size of the repo issue.
